### PR TITLE
Netherite Chests, reopen

### PR DESCRIPTION
**Pull request by unicornbloods**

### CODE REVIEW

**Comment by unicornbloods** [comment]
I never properly disabled the loading on GTNH I will fix that.
I have more changes too (Dark Steel and config to use steel instead of silver)

**Comment by Pilzinsel64** [comment]
Instead checking for the dreamcraft mod you could check for the OreDictionary if there is an entry for netherit. I know ETF also has netherit and I would welcome if iron chest could use that too. :)
Otherwise I'm going to do that some days.

**Comment by chochem** [comment]
checking for GTNH works just fine.

**Comment by unicornbloods** [comment]
> Instead checking for the dreamcraft mod you could check for the OreDictionary if there is an entry for netherit. I know ETF also has netherit and I would welcome if iron chest mod could use that too. :) Otherwise I'm going to do that some days myself.

@Pilzinsel64 There will be a variant for GTNH (dark steel) in my next pushes

**Comment by unicornbloods** [comment]
image
Dark steel

**Comment by chochem** [comment]
will you make a nhcoremod pr for dark steel recipe? probably compressed should then also take the dark steel ones, and there is the upgrade stuff too.

**Comment by chochem** [comment]
from a tester on discord:
image

**Comment by chochem** [comment]
also
image

**Review by chochem — CHANGES_REQUESTED** [review]
should probably mark this as request changes.
please fix bugs and test :)

**Comment by unicornbloods** [comment]
Sorry, I don't make GTNH recipes, those are handled by a seperate mod

**Comment by Ethryan** [comment]
My guess is that you shift the ids for the chests, that way they get everything jumps around like that.

**Review by chochem — CHANGES_REQUESTED** [review]
nope. seems like you still havent even tested it.
[kicked.txt](https://github.com/GTNewHorizons/ironchest/files/14469021/kicked.txt)
also missing texture.

**Comment by chochem** [comment]
they say on discord they have no interest in fixing it

**Comment by unicornbloods** [comment]
I said there is no issue in my use cases. If there is an issue relating to your modpack feel free to help fix it.

**Comment by miaowwwwww** [comment]
image
this is under GTNH, the use case should be GTNH.

**Pull request closed without merging**
