### PR TITLE
fix recipes for non-GTNH environments

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Missed this one line for some reason.

### CODE REVIEW

**Review by Ethryan — APPROVED** [review]

**Comment by unicornbloods** [comment]
It isn't supposed to be usable outside of GTNH. Add a config to disable it please.

**Comment by Pilzinsel64** [comment]
You mean for recipe generation? That's what this PR does, it disable recipes when gtnh is loaded, like before.

**Comment by unicornbloods** [comment]
I realized apparently version 78 has a config option to enable or disable dark steel

**Comment by Pilzinsel64** [comment]
This version also have. I just miss my used the config also here where the check for gtnh were.

**Comment by unicornbloods** [comment]
I see, sounds good!

**Pull request merged**
