### PR TITLE
Implement new chests (from @unicornbloods)

### PR DESCRIPTION
**Pull request by Caedis**
See PR: https://github.com/GTNewHorizons/ironchest/pull/14

Confirmed working in pack.

Need someone to test in an existing world that already has iron chests

### CODE REVIEW

**Review by Pilzinsel64 — COMMENTED** [review]
Ist that intended to use `ingotNetherit` for dark steel chest?

**Comment by Pilzinsel64** [comment]
Also, would it be an idea to also add a config to control netherit/dark steel variants instead of the dreamcraft mod, same as steel/silver variants?
For example, we have both in my private modpack and I either would like to amenable both or only enable dark steel.

I am going to test this PR later this day on a modpack outside gtnh (on my test server) with many gtnh mods. But maybe someone's else still want to try this on an existing gtnh modpack wold.

**Comment by Caedis** [comment]
Feel free to make the changes, just remember that is mod is on the passive list

**Comment by Pilzinsel64** [comment]
Alright, I tested this with some scenarious by turning the config `enableDarkSteelChests` on and off. Existing chests keep like they are but the upgrades mappes fine. There are no missing mappens for FML, so the server starts fine without problem.

What I changed in the source code:
- Add a config `enableDarkSteelChests` wich controls if dark steel chest or nehterit chests will be choosen.
- Use the presence of `dreamcraft` mod as default value for `enableDarkSteelChests`.
- Add mappins for switching between dark steel and netherite chests.
- Add translation for netherite upgrade.
- Use `ingotDarkSteel` for dark steel chests (fixes the non-GTNH recipe)

I've seen that the mappings of turning off `enableSteelChest` are still missing. I consider submitting a seperated PR for this later.

**Comment by Pilzinsel64** [comment]
> just remember that this mod is on the passive list

Sure. That's why I asked before. 😊

**Comment by Pilzinsel64** [comment]
I request another dev to review once as I added own changes and I am not longer in the position to review myself. However, from my side it's a OK. See my comment above.

**Comment by Dream-Master** [comment]
* https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/817
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15641

**Comment by Dream-Master** [comment]
works and tested in GTNH full pack

**Review by Dream-Master — APPROVED** [review]

**Comment by Pilad** [comment]
Silver chest not working
изображение

**Comment by Pilad** [comment]
> See PR: #14
> 
> Confirmed working in pack.
> 
> Need someone to test in an existing world that already has iron chests

Check please silver chest.

**Comment by Caedis** [comment]
@Pilad Can you confirm that with the latest nightly?

**Comment by Pilad** [comment]
> @Pilad Can you confirm that with the latest nightly?

2.6.0 - 389 
изображение
IronChest-6.0.82

**Comment by Caedis** [comment]
Did you spawn that in manually?
Is there a recipe?

**Comment by Caedis** [comment]
I noticed the issue and created a PR for it. Turns out whoever added the iron to silver upgrade forgot to add it to a list.

**Comment by Pilad** [comment]
> I noticed the issue and created a PR for it. Turns out whoever added the iron to silver upgrade forgot to add it to a list.

Thanks for fixing the problem.

**Pull request merged**
