### PR TITLE
Netherite chests

### PR DESCRIPTION
**Pull request by unicornbloods**
It is a netherite chest

### CODE REVIEW

**Comment by Caedis** [comment]
Please provide screenshots of any new additions, including their default recipe.

**Comment by unicornbloods** [comment]
image
image1
image2
image3

**Comment by boubou19** [comment]
Also i don't see any conditional registering, so in its current state, this loads the new chest in NH and we don't want this.

**Comment by unicornbloods** [comment]
> Also i don't see any conditional registering, so in its current state, this loads the new chest in NH and we don't want this.

How do I stop that? I don't do anything for NH

**Comment by Dream-Master** [comment]
> > Also i don't see any conditional registering, so in its current state, this loads the new chest in NH and we don't want this.
> 
> How do I stop that? I don't do anything for NH

All fine we can remove the recipes via core mod and add new ones

**Comment by Dream-Master** [comment]
@unicornbloods How Netherite Ingots made ?

**Comment by Dream-Master** [comment]
ok it was added via MC 1.16. So we need a complete new Gt material for it

**Comment by Dream-Master** [comment]
maybe we rename this Material to something are already in Gt

**Comment by chochem** [comment]
@Dream-Master they dont intend this for GTNH in the first place. and recipes are behind a modload check already. boubou is talking about item registry.

**Comment by Dream-Master** [comment]
> @Dream-Master they dont intend this for GTNH in the first place. and recipes are behind a modload check already. boubou is talking about item registry.

if it is added here it must be GTNH compatible

**Comment by chochem** [comment]
so we should close this and tell them to fork then?

**Comment by unicornbloods** [comment]
Why fork it instead of contributing here and keeping it a central project for the community

**Comment by Cleptomania** [comment]
It should be easy enough to put it behind mod checks, I can add them if we want.

**Comment by mitchej123** [comment]
> if it is added here it must be GTNH compatible

This simply means the beavhior is as is when in NH, and can be different externally.  Just don't register things if dreamcraft is loaded and it's all good.

**Comment by mitchej123** [comment]
We can evaluate later if we want to add netherite to the pack... like if/when EFR happens ;)  It should _not_ be a part of this.

**Comment by unicornbloods** [comment]
I made the new changes!

**Comment by Dream-Master** [comment]
To get the benefit to your new chest just in gtnh why not add a Alu chest similar to Alu Tanks . So the gap between diamond and compressed chest is smaller.

**Comment by unicornbloods** [comment]
What is an Alu? That could be a different PR anyway since it would be a different addition.

**Comment by Dream-Master** [comment]
Aluminium from gt

**Comment by Dream-Master** [comment]
I mean gtnh gt a aluminum alternative . If netherite is present use this .

**Comment by unicornbloods** [comment]
Aluminum after diamond? It could still should be a different pull request lol

**Comment by Dream-Master** [comment]
Not difficult just need to add a second layout of the chest because the color is blueish . If this is to hard we can use other materials with same color ? Dark steel or black steel .

**Comment by unicornbloods** [comment]
Yea it wouldn't be hard for another pr but I also don't make textures

**Comment by Dream-Master** [comment]
Add the texture is the smallest part. If we use dark steel or black steel etc no new texture needed just som code addition

**Comment by unicornbloods** [comment]
Yea we could do that in a different PR for a different chest type

**Comment by Dream-Master** [comment]
It’s not a different chest type just the same chest but we have no netherite in gtnh. This pr is waste for gtnh so I think of a benefit for the pack.

**Comment by Dream-Master** [comment]
What I mean if gtnh is there load gtnh material and recipe if gtnh is not present load netherite (if available as material )

**Comment by unicornbloods** [comment]
There can be a different PR for a different chest type for clarity.

**Comment by Dream-Master** [comment]
Why you close the pr? If you not have the texture just as around. I can did stuff as well.

**Pull request closed without merging**
